config/routes.rb
require 'sidekiq/web'
Mygasmeter::Application.routes.draw do
  get "avresults/presults"
  get "mylocations/show"
  get "monthdata/pay"
  get "alarminfo/show"
  mount Sidekiq::Web, at: '/sidekiq'
  get 'announcements/:id/hide' => 'announcements#hide', as: 'hide_announcement'
  post 'dailydata' => 'dailydata#pay', as: 'pay_dailydata'
  post 'monthdata' => 'monthdata#pay', as: 'pay_monthdata'
  post 'avresults' => 'avresults#presults', as: 'presults_avresults'
  namespace :api do
      namespace :v1 do
        resources :monthcharts
      end
    end
  resources :monthcharts

  get "ltables/create"
  get "ltables/show"
  resources :ltables

  post "lchart/plot"
  resources :gaslocations do
    member do
        get 'preview'
        post 'searchview'
      end
  end
  resources :marklocations
  get "reports/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "allmaps/index"
  devise_for :users
  get '/about'    => 'high_voltage/pages#show', id: 'about'
    get '/contact'  => 'high_voltage/pages#show', id: 'contact'
    get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
    get '/terms'    => 'high_voltage/pages#show', id: 'terms'

    get '/home', to: redirect('/')

    root :to => 'high_voltage/pages#show', id: 'home'
  
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<hrml>
<html ng-app="Raffler">
<head>
  	<meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <meta name="description" content="<%= meta_description %>">
	  <meta name="author" content="<%= meta_author %>">
	  <meta name="Keywords" content="<%= meta_keywords %>">

	  <title><%= full_title(yield(:title)) %></title>
	   
  <%= include_gon %>	  
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%=  javascript_include_tag "//maps.google.com/maps/api/js?sensor=false" %>
  <%= csrf_meta_tags %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'
 type='text/javascript'> </script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
</head>
	<div class="navbar-custom" role="navigation">
	    <div class="container">
	      <div class="navbar-header">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	          <span class="sr-only">Toggle navigation</span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
          
	       Powered by <%= image_tag("/assets/image001.png", :alt => "test image") %>
	      </div>
	      <div class="collapse navbar-collapse">
	        <ul class="nav navbar-nav pull-right">
            <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Site Locations", mylocations_show_path %></li>
	          <li class="<%= 'active' if current_page?(admin_root_path) %>"><%= link_to "Admin", admin_root_path %></li>
	          <li class="<%= 'active' if current_page?(allmaps_index_path) %>"><%= link_to "Geo info", allmaps_index_path %></li> 
             <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Alarm Info", alarminfo_show_path %></li>
	        </ul>
	      </div><!-- /.nav-collapse -->
	    </div><!-- /.container -->
	  </div><!-- /.navbar -->
    <body>
    	<div id="announcementbox">
    	<% Announcement.current(cookies.signed[:hidden_announcement_ids]).each do |announcement| %>
    	  <%= div_for announcement do %>
    	    <%= announcement.message %>
    	    <%= link_to "hide announcement", hide_announcement_path(announcement), remote: true %>
    	  <% end %>
    	<% end %>
    </div>
	<%= yield %>
	<%= yield :scripts %>
	  <% if current_page?(root_path) %>
	    <% if content_for?(:jumbotron) %>
	      <div class="jumbotron">
	        <div class="container">
	          <%= yield :jumbotron %>
	        </div>
	      </div>
	    <% end %>
	  <% else %>
	    <div class="container">
	  <% end %>
	  <footer>
	    <hr>
      
	      <p class="pull-right">
         
	        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
	      </p>
	      <p>
	        &copy; <%= Time.now.year %> <%= site_name %> 
	        &bull;
	        <%= link_to "Privacy", privacy_path %></li>
	        &bull;
	        <%= link_to "Terms", terms_path %></li>
	      </p>
	   
	  </div> <!-- /container -->
	<div class="container" ng-view>
	</div>		
	
	
	
	
	
	
	
	<p class="navbar-text pull-right">
   
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
	
	
	
  <p>Powered by </h3>
  <%= image_tag("/assets/image001.png", :alt => "test image") %>
	
	<% if notice %>
	  <p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-error"><%= alert %></p>
	<% end %>
	 </footer>

</body>

</html>

app/views/layouts/inventory.html.erb
<!DOCTYPE html>
<html>
<head>
  	<meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <meta name="description" content="<%= meta_description %>">
	  <meta name="author" content="<%= meta_author %>">
	  <meta name="Keywords" content="<%= meta_keywords %>">

	  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= yield %>
</body>
	